font:
  catalog:
    merge: true # set value to true to merge catalog with theme you're extending
    Barlow:
      bold: barlowcondensed-semibold.ttf
      bold_italic: barlowcondensed-semibolditalic.ttf
      italic: barlowcondensed-italic.ttf
      normal: barlowcondensed-regular.ttf
      semibold: barlowcondensed-semibold.ttf
      semibold_italic: barlowcondensed-semibolditalic.ttf
    Cairo:  
      bold: cairo-bold.ttf
      bold_italic: cairo-black.ttf
      italic: cairo-black.ttf
      normal: cairo-regular.ttf
      black: cairo-black.ttf
      semibold: cairo-semibold.ttf
    AdventPro: 
      normal: adventpro-light.ttf
      bold: adventpro-bold.ttf
      italic: adventpro-semibold.ttf
      bold_italic: adventpro-thin.ttf
    Arvo:
      bold: arvo-bold.ttf
      bold_italic: arvo-bolditalic.ttf
      italic: arvo-italic.ttf
      normal: arvo-regular.ttf
    Cascadia:
      normal: cascadiamono-regular.ttf
      bold: cascadiamono-bold.ttf
      bold_italic: cascadiamono-semibold.ttf
      italic: cascadiamono-semilight.ttf
extends: default
page:
  layout: portrait
  margin: [0.75in, 1in, 0.75in, 1in]
  size: Letter
base:
  font:
    size: 12
    line-height-length: 15
    line-height: $base-line-height-length / $base-font-size
    family: Barlow
code:
  font:
    size: 10
    line-height-length: 13
    family: Cascadia
    line-height: $base-line-height-length / $base-font-size
heading:
  font:
    family: AdventPro
    style: bold
image:
  border-radius: 15
