= util.sh

Miscellaneous utilities.

* <<arrayhas-element,array.has-element()>>
* <<arrayincludes,array.includes()>>
* <<arraysort,array.sort()>>
* <<arraysort-numeric,array.sort-numeric()>>
* <<arrayuniq,array.uniq()>>
* <<dbpsqldb-settings,db.psql.db-settings()>>
* <<dbconfigparse,db.config.parse()>>
* <<gitopen,git.open()>>
* <<pdfcombine,pdf.combine()>>
* <<utilrot13-stdin,util.rot13-stdin()>>

== array.has-element()

 Returns "true" if the first argument is a member of the array
 passed as the second argument:

=== Example

[source,bash]
----
  $ declare -a array=("a string" test2000 moo)
  if [[ $(array.has-element "a string" "${array[@]}") == "true" ]]; then
    ...
  fi
----

== array.includes()

 Similar to array.has-elements, but does not print anything, just
 returns 0 if includes, 1 if not.

== array.sort()

Sorts the array alphanumerically and prints it to STDOUT

=== Example

[source,bash]
----
  declare -a unsorted=(hello begin again again)
  local sorted="$(array.sort "${unsorted[@]}")"
----

== array.sort-numeric()

Sorts the array numerically and prints it to STDOUT

=== Example

[source,bash]
----
  declare -a unsorted=(1 2 34 45 6)
  local sorted="$(array.sort-numeric "${unsorted[@]}")"
----

== array.uniq()

Sorts and uniqs the array and prints it to STDOUT

=== Example

[source,bash]
----
  declare -a unsorted=(hello hello hello goodbye)
  local uniqued="$(array.sort-numeric "${unsorted[@]}")"
----

== db.psql.db-settings()

Print out PostgreSQL settings for a connection specified by args

=== Example

[source,bash]
----
 db.psql.db-settings -h localhost -U postgres appdb
----

== db.config.parse()

Returns a space-separated values of db host, db name, username and password

=== Example

[source,bash]
----
 db.config.set-file ~/.db/database.yml
 db.config.parse development
 #=> hostname dbname dbuser dbpass
 declare -a params=($(db.config.parse development))
 echo ${params[0]} # host
----

== git.open()

Reads the remote of a repo by name provided as
  an argument (or defaults to "origin") and opens it in the browser.

=== Example

[source,bash]
----
git clone git@github.com:kigster/bashmatic.git
cd bashmatic
source init.sh
git.open
git.open origin # same thing
----

=== Arguments

* *$1* (optional): name of the remote to open, defaults to "orogin"

== pdf.combine()

Combine multiple PDFs into a single one using ghostscript.

=== Example

[source,bash]
----
pdf.combine ~/merged.pdf 'my-book-chapter*'
----

=== Arguments

* *$1* (pathname): to the merged file
* *...* (the): rest of the PDF files to combine

== util.rot13-stdin()

Convert STDIN using rot13

=== Example

[source,bash]
----
 echo "test" | util.rot13-stdin
----
