= util.sh
:doctype: book

Miscellaneous utilities.

* <<arrayhas-element,array.has-element()>>
* <<arrayincludes,array.includes()>>
* <<arraysort,array.sort()>>
* <<arraysort-numeric,array.sort-numeric()>>
* <<arrayuniq,array.uniq()>>
* <<dbpsqldb-settings,db.psql.db-settings()>>
* <<dbconfigparse,db.config.parse()>>
* <<gitopen,git.open()>>
* <<isvalidationerror,__is.validation.error()>>
* <<is-validations,is-validations()>>
* <<isvalidationignore-error,__is.validation.ignore-error()>>
* <<isvalidationreport-error,__is.validation.report-error()>>
* <<whenever,whenever()>>
* <<unless,unless()>>
* <<osxappis-installed,osx.app.is-installed()>>
* <<section,section()>>
* <<is-dbg,is-dbg()>>
* <<dbg,dbg()>>
* <<pathadd,path.add()>>
* <<pathappend,path.append()>>
* <<pathadd,PATH_add()>>
* <<pdfcombine,pdf.combine()>>
* <<shell-setis-set,shell-set.is-set()>>
* <<utilrot13-stdin,util.rot13-stdin()>>

== array.has-element()

 Returns "true" if the first argument is a member of the array
 passed as the second argument:

=== Example

[source,bash]
----
  $ declare -a array=("a string" test2000 moo)
  if [[ $(array.has-element "a string" "${array[@]}") == "true" ]]; then
    ...
  fi
----

== array.includes()

 Similar to array.has-elements, but does not print anything, just
 returns 0 if includes, 1 if not.

== array.sort()

Sorts the array alphanumerically and prints it to STDOUT

=== Example

[source,bash]
----
  declare -a unsorted=(hello begin again again)
  local sorted="$(array.sort "${unsorted[@]}")"
----

== array.sort-numeric()

Sorts the array numerically and prints it to STDOUT

=== Example

[source,bash]
----
  declare -a unsorted=(1 2 34 45 6)
  local sorted="$(array.sort-numeric "${unsorted[@]}")"
----

== array.uniq()

Sorts and uniqs the array and prints it to STDOUT

=== Example

[source,bash]
----
  declare -a unsorted=(hello hello hello goodbye)
  local uniqued="$(array.sort-numeric "${unsorted[@]}")"
----

== db.psql.db-settings()

Print out PostgreSQL settings for a connection specified by args

=== Example

[source,bash]
----
 db.psql.db-settings -h localhost -U postgres appdb
----

== db.config.parse()

Returns a space-separated values of db host, db name, username and password

=== Example

[source,bash]
----
 db.config.set-file ~/.db/database.yml
 db.config.parse development
 #=> hostname dbname dbuser dbpass
 declare -a params=($(db.config.parse development))
 echo ${params[0]} # host
----

== git.open()

Reads the remote of a repo by name provided as
  an argument (or defaults to "origin") and opens it in the browser.

=== Example

[source,bash]
----
git clone git@github.com:kigster/bashmatic.git
cd bashmatic
source init.sh
git.open
git.open origin # same thing
----

=== Arguments

* *$1* (optional): name of the remote to open, defaults to "orogin"

== __is.validation.error()

  Invoke a validation on the value, and process
               the invalid case using a customizable error handler.

=== Arguments

* {blank}
+
= @arg1 func        Validation function name to invoke
* {blank}
+
= @arg2 var         Value under the test
* {blank}
+
= @arg4 error_func  Error function to call when validation fails

[discrete]
=== Exit codes

* *0*: if validation passes

== is-validations()

Returns the list of validation functions available

== __is.validation.ignore-error()

Private function that ignores errors

== __is.validation.report-error()

Private function that ignores errors

== whenever()

a convenient DSL for validating things

=== Example

[source,bash]
----
   whenever /var/log/postgresql.log is.an-empty-file && {
      touch /var/log/postgresql.log
   }
----

== unless()

a convenient DSL for validating things

=== Example

[source,bash]
----
   unless /var/log/postgresql.log is.an-non-empty-file && {
      touch /var/log/postgresql.log
   }
----

== osx.app.is-installed()

@description
  Checks if a given parameter matches any of the installed applications
  under /Applications and ~/Applications

By the default prints the matched application. Pass `-q` as a second
  argument to disable output.

=== Example

[source,bash]
----
 ❯ osx.app.is-installed safari
 Safari.app
 ❯ osx.app.is-installed safari -q && echo installed
 installed
 ❯ osx.app.is-installed microsoft -c
 6
----

=== Arguments

* *$1* (a): string value to match (case insentively) for an app name
* $2.. additional arguments to the last invocation of `grep`

=== Exit codes

* *0*: if match was found
* *1*: if not

== section()

Prints a "arrow-like" line using powerline characters

=== Arguments

* {blank}
+
= @arg1 Width (optional) -- only intepretered as width if the first argument is a number.
* {blank}
+
= @args Text to print

== is-dbg()

Checks if we have debug mode enabled

== dbg()

Local debugging helper, activate it with DEBUG=1

== path.add()

Adds valid directories to those in the PATH and prints
             to the output. DOES NOT MODIFY $PATH

== path.append()

Appends valid directories to those in the PATH, and
             exports the new value of the PATH

== PATH_add()

This function exists within direnv, but since we
             are sourcing in .envrc we need to have this defined
             to avoid errors.

== pdf.combine()

Combine multiple PDFs into a single one using ghostscript.

=== Example

[source,bash]
----
pdf.combine ~/merged.pdf 'my-book-chapter*'
----

=== Arguments

* *$1* (pathname): to the merged file
* *...* (the): rest of the PDF files to combine

== shell-set.is-set()

My super function.
Not thread-safe.

=== Example

[source,bash]
----
 echo "test: $(say-hello World)"
----

=== Arguments

* *$1* (string): A value to print

=== Exit codes

* *0*: If successful.
* *1*: If an empty string passed.

==== See also

* <<validate(),validate()>>

== util.rot13-stdin()

Convert STDIN using rot13

=== Example

[source,bash]
----
 echo "test" | util.rot13-stdin
----
