= Bashmatic© Version 1.2.3
:doctype: article
:allow-uri-read:
:toc:
:toclevels: 5
:sectnums:
:showtitle:

NOTE: https://github.com/reconquest/shdoc[shdoc] documentation extracted from the Bashmatic Sources.

'''
== Module *git*

==== 
Bashmatic Utilities and aliases for Git revision control system. 
==== 


Lots of useful utilities and helpers.

* <<gitopen,git.open()>>

[discrete]
=== git.open()

Reads the remote of a repo by name provided as
  an argument (or defaults to "origin") and opens it in the browser.

[discrete]
==== Example

[source,bash]
----
git clone git@github.com:kigster/bashmatic.git
cd bashmatic
source init.sh
git.open
git.open origin # same thing
----

[discrete]
==== Arguments

* *$1* (optional): name of the remote to open, defaults to "orogin"

== Module *pdf*

==== 
Bashmatic Utilities for PDF file handling 
==== 


Install and uses GhostScript to manipulate PDFs.

* <<pdfcombine,pdf.combine()>>

[discrete]
=== pdf.combine()

Combine multiple PDFs into a single one using ghostscript.

[discrete]
==== Example

[source,bash]
----
pdf.combine ~/merged.pdf 'my-book-chapter*'
----

[discrete]
==== Arguments

* *$1* (pathname): to the merged file
* *...* (the): rest of the PDF files to combine

== Module *util*

==== 
util.sh 
==== 


Miscellaneous utilities.

* <<utilrot13-stdin,util.rot13-stdin()>>

[discrete]
=== util.rot13-stdin()

Convert STDIN using rot13

[discrete]
==== Example

[source,bash]
----
 echo "test" | util.rot13-stdin
----
