= Bashmatic Usage Docs (v1.9.2)
:doctype: book
:allow-uri-read:
:toc:
:toclevels: 5
:sectnums:
:showtitle:
:pdf-fontsdir: ./fonts;GEM_FONTS_DIR
:pdf-theme: .asciidoc-pdf-theme-titilium.yml
:source-highlighter: rouge
:rouge-style: base16.monokai
:icons: font

NOTICE: https://github.com/reconquest/shdoc[shdoc] documentation is auto-extracted from the Bashmatic Sources.

== File `lib/array.sh`

* <<arrayhas-element,array.has-element()>>
* <<arrayincludes,array.includes()>>
* <<arrayjoin,array.join()>>
* <<arraysort,array.sort()>>
* <<arraysort-numeric,array.sort-numeric()>>
* <<arraymin,array.min()>>
* <<arraymax,array.max()>>
* <<arrayuniq,array.uniq()>>

=== array.has-element()

Returns "true" if the first argument is a member of the array
passed as the second argument:

==== Example

[source,bash]
----
$ declare -a array=("a string" test2000 moo)
if [[ $(array.has-element "a string" "${array[@]}") == "true" ]]; then
  ...
fi
----

=== array.includes()

Similar to array.has-elements, but does not print anything, just
returns 0 if includes, 1 if not.

=== array.join()

Joins a given array with a custom character

==== Example

[source,bash]
----
$ declare -a array=(one two three)
$ array.join "," "${array[@]}"
one,two,three
----

=== array.sort()

Sorts the array alphanumerically and prints it to STDOUT

==== Example

[source,bash]
----
declare -a unsorted=(hello begin again again)
local sorted="$(array.sort "${unsorted[@]}")"
----

=== array.sort-numeric()

Sorts the array numerically and prints it to STDOUT

==== Example

[source,bash]
----
declare -a unsorted=(1 2 34 45 6)
local sorted="$(array.sort-numeric "${unsorted[@]}")"
----

=== array.min()

Returns a minimum integer from an array.
Non-numeric elements are ignored and skipped over.
Negative numbers are supported, but non-integers are not.

==== Example

[source,bash]
----
$ declare -a array=(10 20 30 -5 5)
$ array.min "," "${array[@]}"
-5
----

=== array.max()

Returns a maximum integer from an array.
Non-numeric elements are ignored and skipped over.
Negative numbers are supported, but non-integers are not.

==== Example

[source,bash]
----
$ declare -a array=(10 20 30 -5 5)
$ array.min "," "${array[@]}"
30
----

=== array.uniq()

Sorts and uniqs the array and prints it to STDOUT

==== Example

[source,bash]
----
declare -a unsorted=(hello hello hello goodbye)
local uniqued="$(array.sort-numeric "${unsorted[@]}")"
----

'''

== File `lib/asciidoc.sh`

= asciidoc

== Overview

Provides helper functions for dealing with asciidoc format.

* <<asciidocrouge-themes,asciidoc.rouge-themes()>>

=== asciidoc.rouge-themes()

Installs gem "rouge" and prints all available themes

'''

== File `lib/output-utils.sh`

* <<is-dbg,is-dbg()>>
* <<dbg,dbg()>>

=== is-dbg()

Checks if we have debug mode enabled

=== dbg()

Local debugging helper, activate it with DEBUG=1

'''

== File `lib/output.sh`

* <<section,section()>>

=== section()

Prints a "arrow-like" line using powerline characters

==== Arguments

* @arg1 Width (optional) -- only intepretered as width if the first argument is a number.
* @args Text to print

'''

== File `lib/path.sh`

* <<pathadd,path.add()>>
* <<pathappend,path.append()>>
* <<path_add,PATH_add()>>

=== path.add()

Adds valid directories to those in the PATH and prints
to the output. DOES NOT MODIFY $PATH

=== path.append()

Appends valid directories to those in the PATH, and
exports the new value of the PATH

=== PATH_add()

This function exists within direnv, but since we
are sourcing in .envrc we need to have this defined
to avoid errors.

'''

== File `lib/osx.sh`

= osx.sh

== Overview

OSX Specific Helpers and Utilities

* <<osxappis-installed,osx.app.is-installed()>>

=== osx.app.is-installed()

Checks if a given parameter matches any of the installed applications
under /Applications and ~/Applications

By the default prints the matched application. Pass `-q` as a second
argument to disable output.

==== Example

[source,bash]
----
❯ osx.app.is-installed safari
Safari.app
❯ osx.app.is-installed safari -q && echo installed
installed
❯ osx.app.is-installed microsoft -c
6
----

==== Arguments

* *$1* (a): string value to match (case insentively) for an app name
* $2.. additional arguments to the last invocation of `grep`

==== Exit codes

* *0*: if match was found
* *1*: if not

'''

== File `lib/db.sh`

* <<dbconfigparse,db.config.parse()>>
* <<dbpsqlconnect,db.psql.connect()>>
* <<dbpsqlconnectjust-data,db.psql.connect.just-data()>>
* <<dbpsqlconnecttable-settings-set,db.psql.connect.table-settings-set()>>
* <<dbpsqldb-settings,db.psql.db-settings()>>
* <<dbpsqlconnectdb-settings-pretty,db.psql.connect.db-settings-pretty()>>
* <<dbpsqlconnectdb-settings-toml,db.psql.connect.db-settings-toml()>>

=== db.config.parse()

Returns a space-separated values of db host, db name, username and password

==== Example

[source,bash]
----
db.config.set-file ~/.db/database.yml
db.config.parse development
#=> hostname dbname dbuser dbpass
declare -a params=($(db.config.parse development))
echo ${params[0]} # host
----

=== db.psql.connect()

Connect to one of the databases named in the YAML file, and
optionally pass additional arguments to psql.
Informational messages are sent to STDERR.

==== Example

[source,bash]
----
db.psql.connect production
db.psql.connect production -c 'show all'
----

=== db.psql.connect.just-data()

Similar to the db.psql.connect, but outputs
just the raw data with no headers.

==== Example

[source,bash]
----
db.psql.connect.just-data production -c 'select datname from pg_database;'
----

=== db.psql.connect.table-settings-set()

Set per-table settings, such as autovacuum, eg:

==== Example

[source,bash]
----
db.psql.connect.table-settings-set prod users autovacuum_analyze_threshold 1000000
db.psql.connect.table-settings-set prod users autovacuum_analyze_scale_factor 0
----

=== db.psql.db-settings()

Print out PostgreSQL settings for a connection specified by args

==== Example

[source,bash]
----
db.psql.db-settings -h localhost -U postgres appdb
----

=== db.psql.connect.db-settings-pretty()

Print out PostgreSQL settings for a named connection

==== Example

[source,bash]
----
db.psql.connect.db-settings-pretty primary
----

==== Arguments

* @arg1 dbname database entry name in ~/.db/database.yml

=== db.psql.connect.db-settings-toml()

Print out PostgreSQL settings for a named connection using TOML/ini
format.

==== Example

[source,bash]
----
db.psql.connect.db-settings-toml primary > primary.ini
----

==== Arguments

* @arg1 dbname database entry name in ~/.db/database.yml

'''

== File `lib/shdoc.sh`

= lib/shdoc.sh

Helpers to install gawk and shdoc properly.0

== Overview

see `+${BASHMATIC_HOME}/lib/shdoc.md+` for an example of how to use SHDOC.
and also https://github.com/reconquest/shdoc[project's github page].

* <<gawkinstall,gawk.install()>>

=== gawk.install()

Installs gawk into /usr/local/bin/gawk

'''

== File `lib/git.sh`

* <<gitcfgu,git.cfgu()>>
* <<gitopen,git.open()>>

=== git.cfgu()

Sets or gets user values from global gitconfig.

==== Example

[source,bash]
----
git.cfgu email
git.cfgu email kigster@gmail.com
git.cfgu
----

=== git.open()

Reads the remote of a repo by name provided as
an argument (or defaults to "origin") and opens it in the browser.

==== Example

[source,bash]
----
git clone git@github.com:kigster/bashmatic.git
cd bashmatic
source init.sh
git.open
git.open origin # same thing
----

==== Arguments

* *$1* (optional): name of the remote to open, defaults to "orogin"

'''

== File `lib/shasum.sh`

= shasum.sh

SHA Functions

== Overview

SHASUM related functions, that compute SHA for a single file, +
collection of files, or entire directories.

* <<shasumset-command,shasum.set-command()>>
* <<shasumset-algo,shasum.set-algo()>>
* <<shasumsha,shasum.sha()>>
* <<shasumsha-only,shasum.sha-only()>>
* <<shasumsha-only-stdin,shasum.sha-only-stdin()>>
* <<shasumto-hash,shasum.to-hash()>>
* <<shasumall-files,shasum.all-files()>>
* <<shasumall-files-in-dir,shasum.all-files-in-dir()>>

=== shasum.set-command()

Override the default SHA command and alogirthm
Default is shasum -a 256

=== shasum.set-algo()

Override the default SHA algorithm

==== Example

[source,bash]
----
$ shasum.set-algo 256
----

=== shasum.sha()

Compute SHA for all given files, ignore STDERR
NOTE: first few arguments will be passed to the
shasum command, or whatever you set via shasum.set-command.

=== shasum.sha-only()

Print SHA ONLY removing the file components

=== shasum.sha-only-stdin()

Print SHA ONLY removing the file components

=== shasum.to-hash()

This function populates a pre-declare associative array with
filenames mapped to their SHAs, but only in the current directory
Call `dbg-on` to enable additional debugging info.

==== Example

[source,bash]
----
    $ declare -A file_shas
    $ shasum.to-hash file_shas $(find . -type f -maxdepth 2)
    $ echo "Total of ${#file_shas[@]} files in the hash"
----

=== shasum.all-files()

For a given array of files, sort them, take a SHA of each file,
and return a single SHA finger-printing this set of files. #
NOTE: the files are sorted prior to hashing, so the return SHA
should ONLY change when files are either changed, or added/removed.
Only computes SHA of the files provided, does not recurse into folders

==== Example

[source,bash]
----
$ shasum.all-files *.cpp
----

=== shasum.all-files-in-dir()

For a given directory and an optional file pattern,
use `find` to grab every single file (that matches optional pattern)
and return a single SHA

==== Example

[source,bash]
----
$ shasum.all-files-in-dir . '*.pdf'
cc35aad389e61942c75e111f1eddbe634d74b4b1
----

'''

== File `lib/pg.sh`

* <<pgis-running,pg.is-running()>>
* <<pgrunningserver-binaries,pg.running.server-binaries()>>
* <<pgrunningdata-dirs,pg.running.data-dirs()>>
* <<pgserver-in-pathversion,pg.server-in-path.version()>>

=== pg.is-running()

Returns true if PostgreSQL is running locally

=== pg.running.server-binaries()

if one or more PostgreSQL instances is running locally,
prints each server's binary +postgres+ file path

=== pg.running.data-dirs()

For each running server prints the data directory

=== pg.server-in-path.version()

Grab the version from `postgres` binary in the PATH and remove fractional sub-version

'''

== File `lib/dir.sh`

* <<dirshort-home,dir.short-home()>>

=== dir.short-home()

Replaces the first part of the directory that matches $\{HOME} with '~/'

'''

== File `lib/is.sh`

= is.sh

== Overview

Various validations and asserts that can be chained
and be explicit in a DSL-like way.

* <<__isvalidationerror,__is.validation.error()>>
* <<is-validations,is-validations()>>
* <<__isvalidationignore-error,__is.validation.ignore-error()>>
* <<__isvalidationreport-error,__is.validation.report-error()>>
* <<whenever,whenever()>>

=== __is.validation.error()

Invoke a validation on the value, and process
the invalid case using a customizable error handler.

==== Arguments

* @arg1 func        Validation function name to invoke
* @arg2 var         Value under the test
* @arg4 error_func  Error function to call when validation fails

==== Exit codes

* *0*: if validation passes

=== is-validations()

Returns the list of validation functions available

=== __is.validation.ignore-error()

Private function that ignores errors

=== __is.validation.report-error()

Private function that ignores errors

=== whenever()

a convenient DSL for validating things

==== Example

[source,bash]
----
whenever /var/log/postgresql.log is.an-empty-file && {
   touch /var/log/postgresql.log
}
----

'''

== File `lib/util.sh`

= util.sh

== Overview

Miscellaneous utilities.

* <<utilrot13-stdin,util.rot13-stdin()>>

=== util.rot13-stdin()

Convert STDIN using rot13

==== Example

[source,bash]
----
echo "test" | util.rot13-stdin
----

'''

== File `lib/pdf.sh`

= Bashmatic Utilities for PDF file handling

== Overview

Install and uses GhostScript to manipulate PDFs.

* <<pdfcombine,pdf.combine()>>

=== pdf.combine()

Combine multiple PDFs into a single one using ghostscript.

==== Example

[source,bash]
----
pdf.combine ~/merged.pdf 'my-book-chapter*'
----

==== Arguments

* *$1* (pathname): to the merged file
* *...* (the): rest of the PDF files to combine

'''

== File `bin/install-direnv`

= install-direnv

== Overview

Add direnv hook to shell RC files

* <<direnvregister,direnv.register()>>

=== direnv.register()

Add direnv hook to shell RC files

'''

== File `bin/regen-usage-docs`

= regen-usage-docs

== Overview

Regenerates USAGE.adoc && USAGE.pdf

'''

== File `bin/specs`

* <<specsinit,specs.init()>>
* <<specsdetermine-test-filename,specs.determine-test-filename()>>

=== specs.init()

Initialize specs

=== specs.determine-test-filename()

Based on a shortname attempt to determine the actual test file names

'''

== File `bin/pdf-reduce`

* <<pdfdoshrink,pdf.do.shrink()>>

=== pdf.do.shrink()

shrinkgs PDF

'''

== Copyright & License

* Copyright © 2017-2021 Konstantin Gredeskoul, All rights reserved.
* Distributed under the MIT License.
