name: Zsh Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests: 
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.1-alpine
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a health check
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
      
    - name: Install ZSH
      run: 
        sudo apt-get update -yqq && sudo apt-get install -yqq zsh

    - name: Verify that ZSH can source init.sh
      env:
        TERM: xterm-256color
        MIN_WIDTH: 90
      run: zsh -l -c "export DEBUG=1 ; source init.sh"

    - name: Verify that ZSH can run specs
      env:
        TERM: xterm-256color
        MIN_WIDTH: 90
      run: zsh -l -c "export DEBUG=1; bin/specs || true"

